spring:
  application:
    name: kdquiz

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kquiz?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678

  data:
    redis:
      host: localhost
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true

  kdquiz:
    upload:
      path: img

  web:
    resources:
      static-locations:
        - classpath:/static/
        - file:Img/