spring:
  application:
    name: kdquiz

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://localhost:3306/kquiz?serverTimezone=UTC&characterEncoding=UTF-8
    username: root
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    properties:
      hibernate:
        format_sql: true
        show_sql: true